import {Section} from "/js/section-create.js";

sec1 = new Section("Pre Gym 2")
sec1.addMon("Tentacool", 10,110,30,2, "One needs to be male")
sec1.addMon("Plusle", null, 110, null, 1, "One of Plusle, Minun, or Jigglypuff needs to be male")
sec1.addMon("Minun", null, 110, null, 1, "One of Plusle, Minun, or Jigglypuff needs to be male")
sec1.addMon("Electrike", 13, 110, 26, 2)
sec1.addMon("Gulpin", 13, 110, 26, 2)
sec1.addMon("Magikarp", 10, 117, 20, 2)
sec1.addMon("Goldeen", 10, 117 , 33, 2)
sec1.addMon("Oddish", 13, 117, 21, 2)
sec1.addMon("Volbeat", null, 117, null, 1)
sec1.addMon("Illumise", null, 117, null, 1)
sec1.addMon("Torchic", 5, 117, 16, 2)
sec1.addMon("Geodude", 9, "Granite Cave 1F", 25, 2)
sec1.addMon("Zubat", 10, "Granite Cave B1F", 24, 3, ["Catch first to start getting happiness", "You could get a lvl 11 one on B2F, but then you would have to avoid encounters until you come back up"])
sec1.addMon("Makuhita", 11, "Granite Cave B1F", 24, 2)
sec1.addMon("Sableye", null, "Granite Cave B1F", null, 1)
sec1.addMon("Aron", 12, "Granite Cave B2F", "32,42", 3)

sec1.addNote("Grab the bike and rock smash when at mauville")
sec1.addNote("Use the pokemon center in mauville last")
sec1.addNote("Make sure to have teleporter (abra/ralts line) in party when done with section")
sec1.addNote("Total Pokemon obtained should be 66")
sec1.add2Div("sec2")